language: node_js
node_js:
  - "node"
branches:
  only:
  - master
install:
  - yarn
  - yarn build
script:
  - echo "yarn test temporarily disabled"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  on:
    branch: master