language: node_js
node_js:
  - "node"
install:
  - yarn
script:
  - echo "yarn test temporarily disabled"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: feature/ci